"""initial schema

Revision ID: 00e2d7607eb9
Revises: 
Create Date: 2026-09-18 13:32:24.899989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e2d7607eb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('condition_config', sa.JSON(), nullable=False),
    sa.Column('notification_channels', sa.JSON(), nullable=False),
    sa.Column('notification_targets', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_production', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('execution_environments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_run_id', sa.Integer(), nullable=True),
    sa.Column('container_id', sa.String(length=255), nullable=True),
    sa.Column('image_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('creating', 'ready', 'running', 'stopped', 'failed', 'cleaned_up'), nullable=False),
    sa.Column('resource_cpu', sa.Integer(), nullable=True),
    sa.Column('resource_memory', sa.Integer(), nullable=True),
    sa.Column('network_mode', sa.Enum('default', 'none', 'host', 'bridge'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_timestamp'), 'system_metrics', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_rule_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical'), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('database_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('connection_string_encrypted', sa.Text(), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_connection_clearances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.Enum('database', 'storage'), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.Enum('none', 'read', 'write', 'admin'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_permissions',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'permission_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('bucket', sa.String(length=80), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('data_generation_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('prompt_template_id', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('data_schema', sa.JSON(), nullable=False),
    sa.Column('num_rows', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed'), nullable=False),
    sa.Column('result_path', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_type', sa.String(length=100), nullable=True),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version_spec', sa.String(length=255), nullable=False),
    sa.Column('resolved_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_version_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved_qa', 'rejected_qa', 'approved_prod', 'rejected_prod', 'deployed', 'failed', 'rolled_back'), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('rollback_at', sa.DateTime(), nullable=True),
    sa.Column('rollback_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['data_generation_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('framework_version', sa.String(length=50), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(length=512), nullable=True),
    sa.Column('artifact_size', sa.Integer(), nullable=True),
    sa.Column('artifact_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_version_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_parse_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_version_id', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('overall_status', sa.Enum('passed', 'warning', 'failed'), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_version_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.Enum('python', 'sql', 'bash', 'ml_model'), nullable=False),
    sa.Column('script_path', sa.String(length=512), nullable=True),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('approval_type', sa.Enum('qa', 'prod'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependency_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dependency_id', sa.Integer(), nullable=False),
    sa.Column('cache_path', sa.String(length=512), nullable=False),
    sa.Column('cache_size', sa.Integer(), nullable=True),
    sa.Column('cache_hash', sa.String(length=64), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dependency_id')
    )
    op.create_table('deployment_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Enum('debug', 'info', 'warning', 'error', 'critical'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_logs_timestamp'), 'deployment_logs', ['timestamp'], unique=False)
    op.create_table('security_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parse_result_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical'), nullable=False),
    sa.Column('finding_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parse_result_id'], ['security_parse_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_task_id')
    )
    op.create_table('task_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', 'skipped', 'cancelled'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.Enum('scheduler', 'manual', 'api', 'upstream'), nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('execution_environment_id', sa.Integer(), nullable=True),
    sa.Column('log_file_path', sa.String(length=512), nullable=True),
    sa.Column('output_path', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_environment_id'], ['execution_environments.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_run_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Enum('debug', 'info', 'warning', 'error', 'critical'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_timestamp'), 'execution_logs', ['timestamp'], unique=False)
    op.create_table('ml_model_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('task_run_id', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['ml_model_versions.id'], ),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parse_result_id', sa.Integer(), nullable=True),
    sa.Column('task_run_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Enum('debug', 'info', 'warning', 'error', 'critical'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parse_result_id'], ['security_parse_results.id'], ),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_logs_timestamp'), 'security_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###

    # Deferred FK constraints for mutually-dependent tables (use_alter=True on the
    # model side): SQLAlchemy's CreateTable compiler omits these from the inline
    # CREATE TABLE, and alembic's create_table op doesn't emit a follow-up ALTER on
    # its own, so they're added explicitly here once every table exists.
    op.create_foreign_key('fk_execution_environments_task_run_id', 'execution_environments', 'task_runs', ['task_run_id'], ['id'])
    op.create_foreign_key('fk_projects_current_version_id', 'projects', 'project_versions', ['current_version_id'], ['id'])
    op.create_foreign_key('fk_ml_models_current_version_id', 'ml_models', 'ml_model_versions', ['current_version_id'], ['id'])


def downgrade() -> None:
    # Drop the deferred FK constraints before dropping any tables they touch
    op.drop_constraint('fk_ml_models_current_version_id', 'ml_models', type_='foreignkey')
    op.drop_constraint('fk_projects_current_version_id', 'projects', type_='foreignkey')
    op.drop_constraint('fk_execution_environments_task_run_id', 'execution_environments', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_logs_timestamp'), table_name='security_logs')
    op.drop_table('security_logs')
    op.drop_table('ml_model_executions')
    op.drop_index(op.f('ix_execution_logs_timestamp'), table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_table('task_runs')
    op.drop_table('task_dependencies')
    op.drop_table('security_findings')
    op.drop_index(op.f('ix_deployment_logs_timestamp'), table_name='deployment_logs')
    op.drop_table('deployment_logs')
    op.drop_table('dependency_cache')
    op.drop_table('approvals')
    op.drop_table('tasks')
    op.drop_table('security_parse_results')
    op.drop_table('project_files')
    op.drop_table('ml_model_versions')
    op.drop_table('generated_datasets')
    op.drop_table('deployments')
    op.drop_table('dependencies')
    op.drop_table('project_versions')
    op.drop_table('ml_models')
    op.drop_table('data_generation_requests')
    op.drop_table('user_groups')
    op.drop_table('storage_connections')
    op.drop_table('projects')
    op.drop_table('group_permissions')
    op.drop_table('group_connection_clearances')
    op.drop_table('database_connections')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_metrics_timestamp'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_table('prompt_templates')
    op.drop_table('permissions')
    op.drop_table('groups')
    op.drop_table('execution_environments')
    op.drop_table('environments')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
